select NAME, CORES, FREQUENCY
FROM CPU
WHERE CORES >=6
ORDER BY FREQUENCY ASC;


select COUNT(NAME), CORES
FROM CPU
GROUP BY CORES;


select COUNT(NAME), CORES
FROM CPU
GROUP BY CORES
HAVING COUNT (NAME)>200
ORDER BY COUNT(NAME) DESC;


select count(*)
from RAM;


SELECT MIN(FREQUENCY) AS theLowestFrequency
FROM RAM
WHERE TYPE = 'DDR4'; 


SELECT AVG(FREQUENCY) AS averageFrequency
FROM RAM
WHERE TYPE = 'DDR4'; 


SELECT CPU.NAME, CPU.CORES, CPU.FREQUENCY
FROM CPU
INNER JOIN COMPUTER ON COMPUTER.CPU=CPU.ID;


--now full outer join
SELECT CPU.NAME, CPU.CORES, CPU.FREQUENCY
FROM CPU
FULL OUTER JOIN COMPUTER ON COMPUTER.CPU=CPU.ID;


SELECT TEST.COMPUTER_ID, TEST.REVIEW_ID, TEST.CINEBENCH_TOTAL_SCORE
FROM TEST
INNER JOIN COMPUTER ON TEST.COMPUTER_ID=COMPUTER.COMPUTER_ID;


SELECT COMPUTER.NAME, TEST.CINEBENCH_TOTAL_SCORE
FROM TEST
INNER JOIN COMPUTER ON TEST.COMPUTER_ID=COMPUTER.COMPUTER_ID
UNION ALL
SELECT COMPUTER.NAME, TEST.BF3_AVERAGE_FPS
FROM TEST
INNER JOIN COMPUTER ON TEST.COMPUTER_ID=COMPUTER.COMPUTER_ID;


select * 
from (select rownum as wiersz, NAME, CORES
from CPU
order by 2) 
where wiersz between 24 and 51;